package com.hrims.main.frames;

import com.hrims.main.GUIManager;
import com.hrims.main.data.Account;
import com.hrims.main.sql.SQLAccount;
import com.hrims.main.sql.SQLCaller;
import java.sql.Date;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mrdsc
 */
public class Editor_Account extends javax.swing.JInternalFrame implements Updatable {

    /**
     * Creates new form Employee
     */
    
    int pageNumber = 0;
    int numPerPage = 25;
    boolean lockForward = false;
    ArrayList<Account> accounts;
    
    public Editor_Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccount = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDuplicate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        txtPageNumber = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cmbSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Account Editor");
        setMinimumSize(new java.awt.Dimension(1024, 540));
        setPreferredSize(new java.awt.Dimension(1024, 540));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tblAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "test", "guy", "123-456-7890", "qwe@asd.zxc"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Username", "First Name", "Last Name", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAccount.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblAccount);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        btnUpdate.setText("Reload");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnDuplicate.setText("Duplicate");
        btnDuplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuplicateActionPerformed(evt);
            }
        });
        jPanel1.add(btnDuplicate);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrevious);

        txtPageNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPageNumber.setText("1");
        jPanel3.add(txtPageNumber);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel3.add(btnNext);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account ID", "Location ID", "First Name", "Last Name", "Phone", "Company" }));
        cmbSearch.setSelectedIndex(2);
        jPanel4.add(cmbSearch, java.awt.BorderLayout.LINE_START);

        txtSearch.setText("Search");
        jPanel4.add(txtSearch, java.awt.BorderLayout.CENTER);

        btnSearch.setText("Search");
        jPanel4.add(btnSearch, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void Update() {
        accounts = SQLAccount.ME.getAccountsByPage(pageNumber, numPerPage, true);
        Reload();
    }
    
    @Override
    public void Reload() {
        if(accounts.size() > 25) btnNext.setEnabled(true);
        else btnNext.setEnabled(false);
        for(int y = 0; y < tblAccount.getRowCount(); y++) {
            for(int x = 0; x < tblAccount.getColumnCount(); x++) {
                if(y >= accounts.size()) {
                    tblAccount.getModel().setValueAt("", y, x);
                } else {
                    Account a = accounts.get(y);
                    String information = "";
                    switch(x) {
                        case 0:
                            information = ""+a.getUsername();
                            break;
                        case 1:
                            if(a.contacts.size() > 0) {
                                information = ""+a.contacts.get(0).getFirstName();
                            }
                            break;
                        case 2:
                            if(a.contacts.size() > 0) {
                                information = ""+a.contacts.get(0).getLastName();
                            }
                            break;
                        case 3:
                            if(a.contacts.size() > 0) {
                                information = ""+a.contacts.get(0).getMainPhone();
                            }
                            break;
                        case 4:
                            if(a.contacts.size() > 0) {
                                information = ""+a.contacts.get(0).getEmail();
                            }
                            break;
                        }
                    tblAccount.getModel().setValueAt(information, y, x);
                }
            }
        }
        
        txtPageNumber.setText(""+(pageNumber+1));
        if(pageNumber==0) btnPrevious.setEnabled(false);
        
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        try {
            Account acc = new Account();
            Date d = new Date(new java.util.Date().getTime());
            acc.setCreated(d);
            acc.setLastLogin(d);
            Properties_Editor<Account, Editor_Account> editor = (Properties_Editor<Account, Editor_Account>)GUIManager.Lookup("Account_Property_Editor");
            editor.setObject(acc);
            editor.setFrame(this);
            editor.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Update();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(!lockForward) {
            pageNumber++;
            Update();
            if(pageNumber>0) btnPrevious.setEnabled(true);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        pageNumber--;
        if(pageNumber==0) btnPrevious.setEnabled(false);
        lockForward = false;
        Update();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Update();
    }//GEN-LAST:event_formComponentShown

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = tblAccount.getSelectedRow();
        if(row == -1) return;
        try {
            Account acc = accounts.get(row);
            Properties_Editor<Account, Editor_Account> editor = (Properties_Editor<Account, Editor_Account>)GUIManager.Lookup("Account_Property_Editor");
            editor.setObject(acc);
            editor.setFrame(this);
            editor.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        Update();
    }//GEN-LAST:event_formFocusGained

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "Delete selected schedule?");
        if (input == 0){
            int accID = Integer.parseInt((String)tblAccount.getModel().getValueAt(tblAccount.getSelectedRow(), 0));
            
            Account acc = null;
            for(Account a : accounts) {
                if(a.getAccountNumber()== accID) {
                    acc = a;
                }
            }
            
            SQLAccount.ME.deleteAccount(acc);
        }
        Update();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuplicateActionPerformed
        int row = tblAccount.getSelectedRow();
        try 
        {
            int accID = Integer.parseInt((String)tblAccount.getModel().getValueAt(row, 0));
            Account acc = null;
            for(Account m : accounts) 
            {
                if(m.getAccountNumber() == accID) 
                {
                    acc = m;
                }
            }
            Account a = new Account();
            a.setAccess(acc.getAccess());
            a.setAccessRights(acc.getAccessRights());
            a.setCreated(acc.getCreated());
            a.setDiscount(acc.getDiscount());
            a.setLastLogin(acc.getLastLogin());
            
            //a.setUsername(null);
            
            String infoMessage = "Input userame.";
            String titleBar = "Username";
            String s = JOptionPane.showInputDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.ERROR_MESSAGE);
            
            a.setUsername(s);
            
            a.setPassword(a.getPassword());
            
            if(s != null && s != "") {
                SQLAccount.ME.createAccount(a);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        Update();
    }//GEN-LAST:event_btnDuplicateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDuplicate;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAccount;
    private javax.swing.JTextField txtPageNumber;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
