package com.hrims.main.frames;

import com.hrims.main.GUIManager;
import com.hrims.main.data.Machine;
import com.hrims.main.sql.SQLCaller;
import com.hrims.main.sql.SQLMachine;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matthew
 */
public class Editor_Machine extends javax.swing.JInternalFrame implements Updatable
{

    int pageNumber = 0;
    int numPerPage = 25;
    boolean lockForward = false;
    ArrayList<Machine> machines;
    
    /**
     * Creates new form Employee
     */
    public Editor_Machine() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMachine = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();
        btnDuplicate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        txtPageNumber = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Machine Editor");
        setMinimumSize(new java.awt.Dimension(1024, 540));
        setPreferredSize(new java.awt.Dimension(1024, 540));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tblMachine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(1), "Mean Bean Machine (TM)", "02/09/2021", "02/10/2021", null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Machine ID", "Location ID", "Machine Name", "Purchase Date", "Last Use", "In Use"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMachine.setDoubleBuffered(true);
        jScrollPane1.setViewportView(tblMachine);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        jPanel1.add(btnReload);

        btnDuplicate.setText("Duplicate");
        btnDuplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuplicateActionPerformed(evt);
            }
        });
        jPanel1.add(btnDuplicate);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrevious);

        txtPageNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPageNumber.setText("1");
        jPanel3.add(txtPageNumber);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel3.add(btnNext);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jToggleButton3.setText("Search");
        jPanel4.add(jToggleButton3, java.awt.BorderLayout.LINE_END);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Machine ID", "Location ID", "Machine Name", "Purchase Date", "Last Use Date", "InUse" }));
        jComboBox1.setSelectedIndex(2);
        jPanel4.add(jComboBox1, java.awt.BorderLayout.LINE_START);

        jTextField1.setText("Search");
        jPanel4.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try 
        {
            Machine mac = new Machine();
            Date d = new Date(new java.util.Date().getTime());
            mac.setCreated(d);
            mac.setLastUse(d);
            mac.setPurchaseDate(d);
            Properties_Editor<Machine, Editor_Machine> editor = (Properties_Editor<Machine, Editor_Machine>)GUIManager.Lookup("Machine_Property_Editor");
            editor.setObject(mac);
            editor.setFrame(this);
            editor.setVisible(true);
        } 
        catch (Exception ex) 
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        pageNumber--;
        if(pageNumber<0) pageNumber=0;
        Update();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        pageNumber++;
        Update();
    }//GEN-LAST:event_btnNextActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Update();
    }//GEN-LAST:event_formComponentShown

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = tblMachine.getSelectedRow();
        try 
        {
            int macID = Integer.parseInt((String)tblMachine.getModel().getValueAt(row, 0));
            Machine acc = null;
            Properties_Editor<Machine, Editor_Machine> editor = (Properties_Editor<Machine, Editor_Machine>)GUIManager.Lookup("Machine_Property_Editor");
            for(Machine a : machines) 
            {
                if(a.getMachineID() == macID) 
                {
                    acc = a;
                }
            }
            editor.setObject(acc);
            editor.setFrame(this);
            editor.setVisible(true);
        } 
        catch (Exception ex) 
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
    int input = JOptionPane.showConfirmDialog(null, "Delete selected machine?");
    if (input == 0)
    {
        int machineID = Integer.parseInt(tblMachine.getModel().getValueAt(tblMachine.getSelectedRow(), 0).toString());
        SQLMachine.ME.deleteMachine(machineID);
    }
        Update();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        Update();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuplicateActionPerformed
        int row = tblMachine.getSelectedRow();
        try 
        {
            int macID = Integer.parseInt((String)tblMachine.getModel().getValueAt(row, 0));
            Machine mac = null;
            for(Machine m : machines) 
            {
                if(m.getMachineID() == macID) 
                {
                    mac = m;
                }
            }
            Machine m = new Machine();
            m.setCreated(mac.getCreated());
            m.setInUse(mac.isInUse());
            m.setLocationID(mac.getLocationID());
            m.setMachineName(mac.getMachineName());
            m.setPurchaseDate(mac.getPurchaseDate());
            m.setLastUse(mac.getLastUse());
            
            m.Save();
        } 
        catch (Exception ex) 
        {
            ex.printStackTrace();
        }
        Update();
    }//GEN-LAST:event_btnDuplicateActionPerformed

    public void Update() {
        machines = SQLMachine.ME.getMachinesByPage(pageNumber, numPerPage, true);
        if(pageNumber <= 0) btnPrevious.setEnabled(false);
        else btnPrevious.setEnabled(true);
        if(machines.size() > numPerPage) btnNext.setEnabled(true);
        else btnNext.setEnabled(false);     
        Reload();
    }
    
    public void Reload() {
        
        for(int y = 0; y < tblMachine.getRowCount(); y++) {
                for(int x = 0; x < tblMachine.getColumnCount(); x++) {
                if(y >= machines.size()) {
                    tblMachine.getModel().setValueAt("", y, x);
                } else {
                    Machine l = machines.get(y);
                    String information = "";
                    switch(x) {
                        case 0:
                            information = ""+l.getMachineID();
                            break;
                        case 1:
                            information = ""+l.getLocationID();
                            break;
                        case 2:
                            information = ""+l.getMachineName();
                            break;
                        case 3:
                            information = ""+l.getPurchaseDate();
                            break;
                        case 4:
                            information = ""+l.getLastUse();
                            break;
                        case 5:
                            information = ""+l.isInUse();
                            break;
                    }
                    tblMachine.getModel().setValueAt(information, y, x);
                }
            }
        }
        txtPageNumber.setText(""+(pageNumber+1));
        
    }

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) 
    {                                         
        Update();
    }                                                                            

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDuplicate;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnReload;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTable tblMachine;
    private javax.swing.JTextField txtPageNumber;
    // End of variables declaration//GEN-END:variables
}
