package com.hrims.main.frames;

/*
 * This is a license.
 */

/**
 *
 * @author Alexandra Reaman
 */
public class Employee_Interface extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeeInterface
     */
    public Employee_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        employeeID = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        centerPanel = new javax.swing.JPanel();
        centerWestPanel = new javax.swing.JPanel();
        centerEastPanel = new javax.swing.JPanel();
        centerCenterPanel = new javax.swing.JPanel();
        machineIcon = new javax.swing.JLabel();
        beanProductionProgressBar = new javax.swing.JProgressBar();
        machineID = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        southEastPanel = new javax.swing.JPanel();
        southCenterPanel = new javax.swing.JPanel();
        beanProductionButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        southWestPanel = new javax.swing.JPanel();
        southNorthPanel = new javax.swing.JPanel();
        eastPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Employee Machine Activation Process (EMAP)");
        setPreferredSize(new java.awt.Dimension(800, 600));

        northPanel.setMinimumSize(new java.awt.Dimension(100, 50));
        northPanel.setPreferredSize(new java.awt.Dimension(800, 50));
        northPanel.setLayout(new java.awt.BorderLayout());

        employeeID.setText("Employee: ########");
        northPanel.add(employeeID, java.awt.BorderLayout.LINE_START);
        northPanel.add(jSeparator1, java.awt.BorderLayout.SOUTH);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        northPanel.add(jSeparator2, java.awt.BorderLayout.CENTER);

        getContentPane().add(northPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setMaximumSize(new java.awt.Dimension(500, 200));
        centerPanel.setPreferredSize(new java.awt.Dimension(500, 450));
        centerPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout centerWestPanelLayout = new javax.swing.GroupLayout(centerWestPanel);
        centerWestPanel.setLayout(centerWestPanelLayout);
        centerWestPanelLayout.setHorizontalGroup(
            centerWestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        centerWestPanelLayout.setVerticalGroup(
            centerWestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        centerPanel.add(centerWestPanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout centerEastPanelLayout = new javax.swing.GroupLayout(centerEastPanel);
        centerEastPanel.setLayout(centerEastPanelLayout);
        centerEastPanelLayout.setHorizontalGroup(
            centerEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        centerEastPanelLayout.setVerticalGroup(
            centerEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        centerPanel.add(centerEastPanel, java.awt.BorderLayout.LINE_END);

        centerCenterPanel.setLayout(new java.awt.BorderLayout());

        machineIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centerCenterPanel.add(machineIcon, java.awt.BorderLayout.CENTER);
        centerCenterPanel.add(beanProductionProgressBar, java.awt.BorderLayout.SOUTH);

        machineID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        machineID.setText("Machine ########");
        centerCenterPanel.add(machineID, java.awt.BorderLayout.PAGE_START);

        centerPanel.add(centerCenterPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        southPanel.setLayout(new java.awt.BorderLayout());

        southEastPanel.setPreferredSize(new java.awt.Dimension(300, 50));

        javax.swing.GroupLayout southEastPanelLayout = new javax.swing.GroupLayout(southEastPanel);
        southEastPanel.setLayout(southEastPanelLayout);
        southEastPanelLayout.setHorizontalGroup(
            southEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        southEastPanelLayout.setVerticalGroup(
            southEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        southPanel.add(southEastPanel, java.awt.BorderLayout.EAST);

        southCenterPanel.setLayout(new java.awt.BorderLayout());

        beanProductionButton.setText("Produce Beans");
        beanProductionButton.setActionCommand("beanProduction");
        southCenterPanel.add(beanProductionButton, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        southCenterPanel.add(jPanel1, java.awt.BorderLayout.SOUTH);

        southPanel.add(southCenterPanel, java.awt.BorderLayout.CENTER);

        southWestPanel.setPreferredSize(new java.awt.Dimension(300, 50));

        javax.swing.GroupLayout southWestPanelLayout = new javax.swing.GroupLayout(southWestPanel);
        southWestPanel.setLayout(southWestPanelLayout);
        southWestPanelLayout.setHorizontalGroup(
            southWestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        southWestPanelLayout.setVerticalGroup(
            southWestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        southPanel.add(southWestPanel, java.awt.BorderLayout.WEST);

        southNorthPanel.setPreferredSize(new java.awt.Dimension(100, 20));
        southNorthPanel.setLayout(new java.awt.BorderLayout());
        southPanel.add(southNorthPanel, java.awt.BorderLayout.NORTH);

        getContentPane().add(southPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        getContentPane().add(eastPanel, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        getContentPane().add(westPanel, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beanProductionButton;
    private javax.swing.JProgressBar beanProductionProgressBar;
    private javax.swing.JPanel centerCenterPanel;
    private javax.swing.JPanel centerEastPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerWestPanel;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JLabel employeeID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel machineID;
    private javax.swing.JLabel machineIcon;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel southCenterPanel;
    private javax.swing.JPanel southEastPanel;
    private javax.swing.JPanel southNorthPanel;
    private javax.swing.JPanel southPanel;
    private javax.swing.JPanel southWestPanel;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
}
