package com.hrims.main.frames;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Seilum
 */
public class Machine_Breakdown extends javax.swing.JInternalFrame {

    /**
     * Creates new form MachineBreakdownInterface
     */
    public Machine_Breakdown() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        employeeID = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        centerPanel = new javax.swing.JPanel();
        centerWestPanel = new javax.swing.JPanel();
        centerEastPanel = new javax.swing.JPanel();
        centerCenterPanel = new javax.swing.JPanel();
        machineIcon = new javax.swing.JLabel();
        errorFormPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        errorMessage = new javax.swing.JTextField();
        machineLabel = new javax.swing.JLabel();
        machineID = new javax.swing.JTextField();
        decriptionLabel = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        decriptionText = new javax.swing.JTextArea();
        southPanel = new javax.swing.JPanel();
        southCenterPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        southNorthpanel = new javax.swing.JPanel();
        southWestPanel = new javax.swing.JPanel();
        southEastPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        eastPanel = new javax.swing.JPanel();

        setTitle("Submit Ticket");
        setPreferredSize(new java.awt.Dimension(800, 600));

        northPanel.setMinimumSize(new java.awt.Dimension(100, 50));
        northPanel.setPreferredSize(new java.awt.Dimension(800, 50));
        northPanel.setLayout(new java.awt.BorderLayout());

        employeeID.setText("Employee: ########");
        northPanel.add(employeeID, java.awt.BorderLayout.WEST);
        employeeID.getAccessibleContext().setAccessibleName("");

        northPanel.add(jSeparator1, java.awt.BorderLayout.SOUTH);
        jSeparator1.getAccessibleContext().setAccessibleName("");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        northPanel.add(jSeparator2, java.awt.BorderLayout.CENTER);

        getContentPane().add(northPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout centerWestPanelLayout = new javax.swing.GroupLayout(centerWestPanel);
        centerWestPanel.setLayout(centerWestPanelLayout);
        centerWestPanelLayout.setHorizontalGroup(
            centerWestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        centerWestPanelLayout.setVerticalGroup(
            centerWestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        centerPanel.add(centerWestPanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout centerEastPanelLayout = new javax.swing.GroupLayout(centerEastPanel);
        centerEastPanel.setLayout(centerEastPanelLayout);
        centerEastPanelLayout.setHorizontalGroup(
            centerEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        centerEastPanelLayout.setVerticalGroup(
            centerEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        centerPanel.add(centerEastPanel, java.awt.BorderLayout.LINE_END);

        centerCenterPanel.setLayout(new java.awt.BorderLayout());

        machineIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centerCenterPanel.add(machineIcon, java.awt.BorderLayout.NORTH);

        errorFormPanel.setLayout(new java.awt.GridLayout(0, 2));

        errorLabel.setLabelFor(errorMessage);
        errorLabel.setText("Error:");
        errorFormPanel.add(errorLabel);

        errorMessage.setEditable(false);
        errorMessage.setText("I am Error.");
        errorMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorMessageActionPerformed(evt);
            }
        });
        errorFormPanel.add(errorMessage);

        machineLabel.setLabelFor(machineID);
        machineLabel.setText("Machine");
        errorFormPanel.add(machineLabel);

        machineID.setEditable(false);
        machineID.setText("########");
        errorFormPanel.add(machineID);

        decriptionLabel.setLabelFor(decriptionText);
        decriptionLabel.setText("Decription");
        errorFormPanel.add(decriptionLabel);

        decriptionText.setColumns(20);
        decriptionText.setRows(5);
        descriptionScrollPane.setViewportView(decriptionText);

        errorFormPanel.add(descriptionScrollPane);

        centerCenterPanel.add(errorFormPanel, java.awt.BorderLayout.CENTER);

        centerPanel.add(centerCenterPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        southPanel.setLayout(new java.awt.BorderLayout());

        southCenterPanel.setPreferredSize(new java.awt.Dimension(800, 100));
        southCenterPanel.setLayout(new java.awt.BorderLayout());

        submitButton.setText("Submit");
        submitButton.setActionCommand("submitButton");
        southCenterPanel.add(submitButton, java.awt.BorderLayout.CENTER);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        southCenterPanel.add(jPanel1, java.awt.BorderLayout.SOUTH);

        southPanel.add(southCenterPanel, java.awt.BorderLayout.CENTER);

        southNorthpanel.setPreferredSize(new java.awt.Dimension(800, 25));

        javax.swing.GroupLayout southNorthpanelLayout = new javax.swing.GroupLayout(southNorthpanel);
        southNorthpanel.setLayout(southNorthpanelLayout);
        southNorthpanelLayout.setHorizontalGroup(
            southNorthpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        southNorthpanelLayout.setVerticalGroup(
            southNorthpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        southPanel.add(southNorthpanel, java.awt.BorderLayout.NORTH);

        southWestPanel.setPreferredSize(new java.awt.Dimension(300, 100));

        javax.swing.GroupLayout southWestPanelLayout = new javax.swing.GroupLayout(southWestPanel);
        southWestPanel.setLayout(southWestPanelLayout);
        southWestPanelLayout.setHorizontalGroup(
            southWestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        southWestPanelLayout.setVerticalGroup(
            southWestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        southPanel.add(southWestPanel, java.awt.BorderLayout.WEST);

        southEastPanel.setPreferredSize(new java.awt.Dimension(300, 100));

        javax.swing.GroupLayout southEastPanelLayout = new javax.swing.GroupLayout(southEastPanel);
        southEastPanel.setLayout(southEastPanelLayout);
        southEastPanelLayout.setHorizontalGroup(
            southEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        southEastPanelLayout.setVerticalGroup(
            southEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        southPanel.add(southEastPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(southPanel, java.awt.BorderLayout.PAGE_END);

        westPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        getContentPane().add(westPanel, java.awt.BorderLayout.LINE_START);

        eastPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        getContentPane().add(eastPanel, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void errorMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorMessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerCenterPanel;
    private javax.swing.JPanel centerEastPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerWestPanel;
    private javax.swing.JLabel decriptionLabel;
    private javax.swing.JTextArea decriptionText;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JLabel employeeID;
    private javax.swing.JPanel errorFormPanel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField errorMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField machineID;
    private javax.swing.JLabel machineIcon;
    private javax.swing.JLabel machineLabel;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel southCenterPanel;
    private javax.swing.JPanel southEastPanel;
    private javax.swing.JPanel southNorthpanel;
    private javax.swing.JPanel southPanel;
    private javax.swing.JPanel southWestPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
}
