package com.hrims.main.frames;

import com.hrims.main.GUIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Seilum
 */
public class Menu_Employee extends javax.swing.JInternalFrame {

    /** Creates new form EmployeeMiddleGUI */
    public Menu_Employee() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewScheduleButton = new javax.swing.JButton();
        OperateMachineButton = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Employee Menu");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        ViewScheduleButton.setText("View Schedule");
        ViewScheduleButton.setActionCommand("ViewSchedule");
        ViewScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewScheduleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewScheduleButton);
        ViewScheduleButton.getAccessibleContext().setAccessibleName("ViewSchedule");

        OperateMachineButton.setText("Operate Machine");
        OperateMachineButton.setActionCommand("OperateMachine");
        OperateMachineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperateMachineButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OperateMachineButton);

        jToggleButton1.setText("Help Tickets");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewScheduleButtonActionPerformed
        GUIManager.Show("Schedule_Viewer");
    }//GEN-LAST:event_ViewScheduleButtonActionPerformed

    private void OperateMachineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperateMachineButtonActionPerformed
        GUIManager.Show("Employee_Interface");
    }//GEN-LAST:event_OperateMachineButtonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        GUIManager.Show("TicketList");
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OperateMachineButton;
    private javax.swing.JButton ViewScheduleButton;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
