package com.hrims.main.frames;

import com.hrims.main.GUIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Justin
 */
public class Menu_Main extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_Main
     */
    public Menu_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSettings = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Main Menu");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridLayout(5, 1));

        btnEmployeeMenu.setText("Employee Menu");
        btnEmployeeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmployeeMenu);

        btnDistributorMenu.setText("Distributor Menu");
        btnDistributorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributorMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnDistributorMenu);

        btnManagerMenu.setText("Manager Menu");
        btnManagerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnManagerMenu);

        btnAdministratorMenu.setText("Administrator Menu");
        btnAdministratorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministratorMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministratorMenu);

        btnSettings.setText("Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSettings);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeMenuActionPerformed
        GUIManager.Show("Employee_Frame");
    }//GEN-LAST:event_btnEmployeeMenuActionPerformed

    private void btnManagerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerMenuActionPerformed
        GUIManager.Show("Manager_Frame");
    }//GEN-LAST:event_btnManagerMenuActionPerformed

    private void btnAdministratorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministratorMenuActionPerformed
        GUIManager.Show("Administrator_Frame");
    }//GEN-LAST:event_btnAdministratorMenuActionPerformed

    private void btnDistributorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributorMenuActionPerformed
        GUIManager.Show("Distributor_Menu");
    }//GEN-LAST:event_btnDistributorMenuActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        GUIManager.Show("Settings");
    }//GEN-LAST:event_btnSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JButton btnAdministratorMenu = new javax.swing.JButton();
    public static final javax.swing.JButton btnDistributorMenu = new javax.swing.JButton();
    public static final javax.swing.JButton btnEmployeeMenu = new javax.swing.JButton();
    public static final javax.swing.JButton btnManagerMenu = new javax.swing.JButton();
    private javax.swing.JButton btnSettings;
    // End of variables declaration//GEN-END:variables
}
