/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hrims.main.frames;

/**
 *
 * @author Justin
 */
public class Startup_ProgressBar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Startup_ProgressBar
     */
    public Startup_ProgressBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barProgress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Loading, Please Wait...");
        setMinimumSize(new java.awt.Dimension(500, 60));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 60));
        getContentPane().add(barProgress, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barProgress;
    // End of variables declaration//GEN-END:variables

    public void setMaxVal(int i) {
        barProgress.setMaximum(i);
    }

    public void increment() {
        if(barProgress.getValue() < barProgress.getMaximum()) {
            barProgress.setValue(barProgress.getValue() + 1);
        }
    }
}
