package com.hrims.main.frames;

import com.hrims.main.data.Ticket;
import com.hrims.main.sql.SQLTicket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Justin
 */
public class Ticket_AddResponse extends javax.swing.JInternalFrame {

    Ticket ticket;
    Ticket_Page page;
    
    /**
     * Creates new form GUI_Distributor
     */
    public Ticket_AddResponse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAddResponse = new javax.swing.JButton();
        btnCancel = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResponse = new javax.swing.JTextArea();

        setTitle("New Response");
        setMinimumSize(new java.awt.Dimension(1024, 550));
        setPreferredSize(new java.awt.Dimension(1024, 550));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnAddResponse.setText("Add Response");
        btnAddResponse.setFocusable(false);
        btnAddResponse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddResponse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddResponseActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddResponse);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        txtResponse.setColumns(20);
        txtResponse.setRows(5);
        txtResponse.setText("Description");
        jScrollPane2.setViewportView(txtResponse);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddResponseActionPerformed
        if(SQLTicket.ME.AddResponse(ticket, txtResponse.getText())) {
            
            this.page.Update();
            this.ticket = null;
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnAddResponseActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.ticket = null;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket_AddResponse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket_AddResponse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket_AddResponse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_AddResponse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket_AddResponse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddResponse;
    private javax.swing.JToggleButton btnCancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtResponse;
    // End of variables declaration//GEN-END:variables

    void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }

    void setPage(Ticket_Page page) {
        this.page = page;
    }
}
